### ISSUE TITLE
OSError: mysql_config not found

### ISSUE THREAD

**Issue by morris821028** [JudgeGirl/Judge-sender#4]
```
root@supermicro:/home/judgesister/Judge-sender/install_tutorial/MySQL-for-Python-3# python3 setup.py install
/bin/sh: 1: mysql_config: not found
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    metadata, options = get_config()
  File "/home/judgesister/Judge-sender/install_tutorial/MySQL-for-Python-3/setup_posix.py", line 43, in get_config
    libs = mysql_config("libs_r")
  File "/home/judgesister/Judge-sender/install_tutorial/MySQL-for-Python-3/setup_posix.py", line 25, in mysql_config
    raise EnvironmentError("{} not found".format(mysql_config.path))
OSError: mysql_config not found
```

**Comment by morris821028** [comment]
http://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface

**Comment by morris821028** [comment]
mySQLdb is a python interface for mysql, but it is not mysql itself. And apparently mySQLdb needs the command 'mysql_config', so you need to install that first.

Can you confirm that you did or did not install mysql itself, by running "mysql" from the shell? That should give you a response other than "mysql: command not found".

Which linux distribution are you using? Mysql is pre-packaged for most linux distributions. For example, for debian / ubuntu, installing mysql is as easy as

```
sudo apt-get install mysql
```

mysql-config is in a different package, which can be installed from (again, assuming debian / ubuntu):

```
sudo apt-get install libmysqlclient-dev
```

if you are using mariadb, the drop in replacement for mysql, then run

```
sudo apt-get install libmariadbclient-dev
```

**Comment by pulkitpahwa2512** [comment]
(mac specific answer) I have tried a lot many things, but these set of commands finally worked for me. 

1. `brew install mysql` # install mysql
2. `brew unlink mysql` 
3. `brew install mysql-connector-c`
4. `export PATH=/usr/local/Cellar/mysql/8.0.11/bin:$PATH`  # update path and set the mysql bin folder to path
5. `sudo ln -s /usr/local/Cellar/mysql/8.0.11/lib/libmysqlclient.21.dylib /usr/local/Cellar/lib/libmysqlclient.21.dylib` # create symlink 
6. `pip install mysqlclient`  # install mysql-client finally

**Comment by mobinalhassan** [comment]
Easy solution step by step work for me and work for almost everyone!
1st You need to install apt-get package
`sudo apt-get install mysql-server`
`sudo apt-get install libmysqlclient-dev`
`sudo apt-get install libmariadbclient-dev`
2nd you need to install pip package
`pip install mysqlclient`
then you are ready to install any package which have problem of 
> python setup.py egg_info Check

`pip install your-package-name`

**Comment by bcichowlas** [comment]
I'm on Big Sur and have been stuck on this problem for awhile.  I tried what pulkitpahwa2512 suggested and was doing fine until the last step.  At that point, I got EnvironmentError: mysql_config not found, which of course was what I was trying to avoid.  I suppose I can go back and try the same on Catalina.

**Comment by karthicraghupathi** [comment]
@bcichowlas On Big Sur, if you are using `brew`, you can run `brew install mysql@5.7`. Once that is complete, you should be able to install `mysqlclient`

**Comment by sadric5** [comment]
I'm using Big Sur 
run the command:
 `pip install msql ` and it should install mysql and mysqlclient  for you. Otherwise, after 
`pip install mysql`  run the command 
`pip install mysqlclient` separate.

**Comment by alltufan** [comment]
when ı type "brew install mysql" in my mac shell, ı am getting command not found warning. 

sadric5 : I installed msql but when ı tried to install mysql ı got " raise OSError("{} not found".format(_mysql_config_path))" this error message. 

Also sudo apt-get install mysql-server when ı try this code ı am still taking same warning that command not found
